### ISSUE TITLE
Killing mob using Mace enchanted with Wind Burst creates fake #explosion logs 

### ISSUE THREAD

**Issue by thehaffk** [PlayPro/CoreProtect#555]
Video: https://imgur.com/aWzd0uA 

We are using Paper 1.20.6-138-master with new 1.21 features with enabled "update_1_21"

**Comment by thehaffk** [comment]
This still happens on v23.0-RC1
![image](https://github.com/user-attachments/assets/5f581a22-7763-4f63-9944-b6c34b43c0cd)

also triggered when wind charge is fired

**Comment by Intelli** [comment]
Please provide the exact steps to replicate

**Comment by thehaffk** [comment]
> Please provide the exact steps to replicate

I believe they are exact same like in original issue: smash something with mace enchanted with wind charge or just use wind charge (https://imgur.com/aWzd0uA)
![image](https://github.com/user-attachments/assets/05789352-0aa8-4709-b1e1-f7fdf16591fa)
also using wind charge switches levers, but doesnt log anything

I thought it was fixed in latest RC, so i built 23.2 locally
![image](https://github.com/user-attachments/assets/08840338-3632-43ce-907f-0aedf987723e)

I also used CoreProtect TNT, so i've deleted it, results were the same

**Comment by DereC4** [comment]
This still happens to me as well when players use wind charge; fake explosion logs are created
